//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_ToggleGroupHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.UI.ToggleGroupHelper), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Init", new LuaCSFunction(Init));
		L.RegFunction("__eq", new LuaCSFunction(op_Equality));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("content", new LuaCSFunction(get_content), new LuaCSFunction(set_content));
		L.RegVar("defaultActiveIndex", new LuaCSFunction(get_defaultActiveIndex), new LuaCSFunction(set_defaultActiveIndex));
		L.RegVar("onToggleGroupSelected", new LuaCSFunction(get_onToggleGroupSelected), new LuaCSFunction(set_onToggleGroupSelected));
		L.RegVar("onToggleGroupSelectedAction", new LuaCSFunction(get_onToggleGroupSelectedAction), new LuaCSFunction(set_onToggleGroupSelectedAction));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UI.ToggleGroupHelper obj = (UnityEngine.UI.ToggleGroupHelper)ToLua.CheckObject<UnityEngine.UI.ToggleGroupHelper>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_content(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.ToggleGroupHelper obj = (UnityEngine.UI.ToggleGroupHelper)o;
			UnityEngine.RectTransform ret = obj.content;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index content on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_defaultActiveIndex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.ToggleGroupHelper obj = (UnityEngine.UI.ToggleGroupHelper)o;
			int ret = obj.defaultActiveIndex;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index defaultActiveIndex on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onToggleGroupSelected(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.ToggleGroupHelper obj = (UnityEngine.UI.ToggleGroupHelper)o;
			UnityEngine.UI.ToggleGroupHelper.ToggleGroupSelectedEvent ret = obj.onToggleGroupSelected;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onToggleGroupSelected on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onToggleGroupSelectedAction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.ToggleGroupHelper obj = (UnityEngine.UI.ToggleGroupHelper)o;
			System.Action<int> ret = obj.onToggleGroupSelectedAction;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onToggleGroupSelectedAction on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_content(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.ToggleGroupHelper obj = (UnityEngine.UI.ToggleGroupHelper)o;
			UnityEngine.RectTransform arg0 = (UnityEngine.RectTransform)ToLua.CheckObject<UnityEngine.RectTransform>(L, 2);
			obj.content = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index content on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_defaultActiveIndex(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.ToggleGroupHelper obj = (UnityEngine.UI.ToggleGroupHelper)o;
			int arg0 = (int)LuaDLL.luaL_checkinteger(L, 2);
			obj.defaultActiveIndex = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index defaultActiveIndex on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onToggleGroupSelected(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.ToggleGroupHelper obj = (UnityEngine.UI.ToggleGroupHelper)o;
			UnityEngine.UI.ToggleGroupHelper.ToggleGroupSelectedEvent arg0 = (UnityEngine.UI.ToggleGroupHelper.ToggleGroupSelectedEvent)ToLua.CheckObject<UnityEngine.UI.ToggleGroupHelper.ToggleGroupSelectedEvent>(L, 2);
			obj.onToggleGroupSelected = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onToggleGroupSelected on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onToggleGroupSelectedAction(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.ToggleGroupHelper obj = (UnityEngine.UI.ToggleGroupHelper)o;
			System.Action<int> arg0 = (System.Action<int>)ToLua.CheckDelegate<System.Action<int>>(L, 2);

			if (!object.ReferenceEquals(obj.onToggleGroupSelectedAction, arg0))
			{
				if (obj.onToggleGroupSelectedAction != null) obj.onToggleGroupSelectedAction.SubRef();
				obj.onToggleGroupSelectedAction = arg0;
			}

			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onToggleGroupSelectedAction on a nil value");
		}
	}
}

